name = "vaishnavi-innovations-website"
type = "javascript"

account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
upload.format = "modules"
upload.dir = "./dist"
