name = "your-project-name"
main = "./dist/index.js"  # Make sure this file exists
compatibility_date = "2024-03-22"

[build]
command = "npm run build"  # Your build command
upload.format = "modules"   # Or "service-worker" depending on your setup
